version: "3.9"

services:
  db:
    image: postgres:16
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb
    ports:
      - "5433:5432"         # host:container (use 5433 locally to avoid clashing with a local Postgres)
    volumes:
      - pg_data:/var/lib/postgresql/data
      # Runs once on first init (i.e., empty volume)
      - ./migrations/up.pg.sql:/docker-entrypoint-initdb.d/001-up.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
