version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: my_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      # ⬇️ This runs once on first init (empty volume)
      - ./migrations/up.sql:/docker-entrypoint-initdb.d/001-up.sql:ro

volumes:
  db_data:
