-- ===== Helpers: updated_at trigger =====
CREATE OR REPLACE FUNCTION set_timestamp()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ===== Clean up (drop in right order) =====
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS collections CASCADE;
DROP TABLE IF EXISTS product_types CASCADE;
DROP TABLE IF EXISTS about_json CASCADE;
DROP TABLE IF EXISTS contact_json CASCADE;

-- ===== Reference tables =====

CREATE TABLE collections (
  slug TEXT PRIMARY KEY,
  title TEXT NOT NULL UNIQUE,
  header_image TEXT,
  description TEXT
);

CREATE TABLE product_types (
  slug TEXT PRIMARY KEY,
  title TEXT NOT NULL UNIQUE
);

-- ===== Custom enum type for product availability =====
CREATE TYPE availability_status AS ENUM (
  'available',    -- item can be bought
  'out_of_stock', -- temporarily unavailable, might restock
  'sold'          -- one-of-one / permanently gone
);

-- ===== Products =====
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC(10,2) NOT NULL,
  collection_slug TEXT NOT NULL REFERENCES collections(slug) ON DELETE CASCADE,
  type_slug TEXT NOT NULL REFERENCES product_types(slug) ON DELETE CASCADE,

  -- CHANGED: images are now an array of URLs
  image_urls TEXT[] NOT NULL DEFAULT '{}',

  quantity INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  colors JSONB NOT NULL DEFAULT '[]', -- array of objects: [{name: "Noir", hex: "#000000"}]
  has_quantity BOOLEAN NOT NULL DEFAULT TRUE, -- if false, "1 piece only" or untracked
  description TEXT NOT NULL DEFAULT '',

  -- availability now fully controlled by backend, NOT tied to quantity
  availability availability_status NOT NULL DEFAULT 'available',

  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_products_collection_slug ON products (collection_slug);
CREATE INDEX ix_products_type_slug       ON products (type_slug);
CREATE INDEX ix_products_price           ON products (price);
CREATE INDEX ix_products_name            ON products (name);
CREATE INDEX ix_products_colors_gin      ON products USING gin (colors);
CREATE INDEX ix_products_availability    ON products (availability);

-- Optional but useful if you ever search inside the array:
-- CREATE INDEX ix_products_image_urls_gin ON products USING gin (image_urls);

-- ===== JSON tables =====
CREATE TABLE about_json (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_slug TEXT NOT NULL UNIQUE,
  data JSONB NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE contact_json (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_slug TEXT NOT NULL UNIQUE,
  data JSONB NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ===== Orders & items =====
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_status') THEN
    CREATE TYPE order_status AS ENUM ('pending','processing','shipped','delivered','cancelled');
  END IF;
END$$;

CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id TEXT NOT NULL UNIQUE,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  shipping_address TEXT NOT NULL,
  order_notes TEXT,
  total_amount NUMERIC(10,2) NOT NULL,
  status order_status DEFAULT 'pending',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_orders_order_id        ON orders (order_id);
CREATE INDEX ix_orders_customer_email  ON orders (customer_email);
CREATE INDEX ix_orders_status          ON orders (status);
CREATE INDEX ix_orders_created_at      ON orders (created_at);

CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id TEXT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  quantity INT NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(10,2) NOT NULL,
  total_price NUMERIC(10,2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_order_items_order_id   ON order_items (order_id);
CREATE INDEX ix_order_items_product_id ON order_items (product_id);

-- ===== Triggers for updated_at =====
CREATE TRIGGER trg_products_set_timestamp
BEFORE UPDATE ON products
FOR EACH ROW EXECUTE FUNCTION set_timestamp();

CREATE TRIGGER trg_about_json_set_timestamp
BEFORE UPDATE ON about_json
FOR EACH ROW EXECUTE FUNCTION set_timestamp();

CREATE TRIGGER trg_contact_json_set_timestamp
BEFORE UPDATE ON contact_json
FOR EACH ROW EXECUTE FUNCTION set_timestamp();

CREATE TRIGGER trg_orders_set_timestamp
BEFORE UPDATE ON orders
FOR EACH ROW EXECUTE FUNCTION set_timestamp();

-- ===== Seed data =====

-- collections
INSERT INTO collections (slug, title, header_image, description) VALUES
('summer-2024','Summer Collection 2024','https://placehold.co/1920x600/1a1a1a/ffffff','Discover our exclusive designs'),
('spring-elegance','Spring Elegance','https://placehold.co/1920x600/1a1a1a/ffffff','Discover our exclusive designs'),
('winter-dreams','Winter Dreams','https://placehold.co/1920x600/1a1a1a/ffffff','Discover our exclusive designs'),
('autumn-mystery','Autumn Mystery','https://placehold.co/1920x600/1a1a1a/ffffff','Discover our exclusive designs')
ON CONFLICT (slug) DO UPDATE
SET title=EXCLUDED.title,
    header_image=EXCLUDED.header_image,
    description=EXCLUDED.description;

-- product_types (FIXED: removed trailing comma)
INSERT INTO product_types (slug, title) VALUES
('undies','Undies')
ON CONFLICT (slug) DO UPDATE
SET title=EXCLUDED.title;

-- products with hex colors (migrated to JSONB objects)
-- CHANGED: image_urls is now TEXT[] (array of urls)
-- FIXED: removed trailing comma after the row
INSERT INTO products (id, name, price, collection_slug, type_slug, image_urls, quantity, colors, has_quantity, description)
VALUES
(
  1,
  'Elegant Noir',
  199.99,
  'summer-2024',
  'undies',
  ARRAY[
    'https://placehold.co/600x800/1a1a1a/ffffff',
    'https://placehold.co/600x800/000000/ffffff'
  ],
  25,
  '[{"name": "#000000", "hex": "#000000"}, {"name": "#FF0000", "hex": "#FF0000"}]'::jsonb,
  true,
  'Refined, premium piece.'
)
ON CONFLICT (id) DO UPDATE
SET name=EXCLUDED.name,
    price=EXCLUDED.price,
    collection_slug=EXCLUDED.collection_slug,
    type_slug=EXCLUDED.type_slug,
    image_urls=EXCLUDED.image_urls,
    quantity=EXCLUDED.quantity,
    colors=EXCLUDED.colors,
    description=EXCLUDED.description;

SELECT setval(pg_get_serial_sequence('products','id'), (SELECT MAX(id) FROM products), true);

-- about_json
INSERT INTO about_json (key_slug, data) VALUES
('about', jsonb_build_object(
  'title', 'About CocoCulotte',
  'sections', jsonb_build_array(
    jsonb_build_object('title','Our Story','text','Founded with a passion for elegant design and sustainable fashion, CocoCulotte represents the perfect blend of style and consciousness.','image','/images/IMG_0775.JPG'),
    jsonb_build_object('title','Our Vision','text','We envision a world where fashion meets responsibility.','image','/images/IMG_0778.JPG'),
    jsonb_build_object('title','Our Promise','text','Quality and sustainability are at the heart of everything we do.','image','/images/IMG_0785.JPG')
  )
));

-- contact_json
INSERT INTO contact_json (key_slug, data) VALUES
('contact', jsonb_build_object(
  'headline', 'Get in Touch',
  'intro', 'Have questions about our collections or need assistance? We''re here to help you find the perfect piece.',
  'store', jsonb_build_object(
    'address', '123 Fashion Street',
    'cityCountry', 'Paris, France',
    'hours', 'Mon-Sat: 10am - 7pm'
  )
));



-- add order_pk_id on order_items
ALTER TABLE order_items ADD COLUMN order_pk_id BIGINT;

-- backfill
UPDATE order_items oi
SET order_pk_id = o.id
FROM orders o
WHERE o.order_id = oi.order_id;

-- make it required
ALTER TABLE order_items ALTER COLUMN order_pk_id SET NOT NULL;

-- add FK
ALTER TABLE order_items
  ADD CONSTRAINT fk_order_items_orders_id
  FOREIGN KEY (order_pk_id) REFERENCES orders(id) ON DELETE CASCADE;

-- index
CREATE INDEX IF NOT EXISTS ix_order_items_order_pk_id ON order_items(order_pk_id);

-- optional: drop old text FK later once app is updated
-- ALTER TABLE order_items DROP CONSTRAINT ... (if any)
-- ALTER TABLE order_items DROP COLUMN order_id;


ALTER TABLE products     ALTER COLUMN created_at TYPE timestamptz USING created_at AT TIME ZONE 'UTC';
ALTER TABLE products     ALTER COLUMN updated_at TYPE timestamptz USING updated_at AT TIME ZONE 'UTC';
ALTER TABLE orders       ALTER COLUMN created_at TYPE timestamptz USING created_at AT TIME ZONE 'UTC';
ALTER TABLE orders       ALTER COLUMN updated_at TYPE timestamptz USING updated_at AT TIME ZONE 'UTC';
ALTER TABLE about_json   ALTER COLUMN created_at TYPE timestamptz USING created_at AT TIME ZONE 'UTC';
ALTER TABLE about_json   ALTER COLUMN updated_at TYPE timestamptz USING updated_at AT TIME ZONE 'UTC';
ALTER TABLE contact_json ALTER COLUMN created_at TYPE timestamptz USING created_at AT TIME ZONE 'UTC';
ALTER TABLE contact_json ALTER COLUMN updated_at TYPE timestamptz USING updated_at AT TIME ZONE 'UTC';
ALTER TABLE order_items  ALTER COLUMN created_at TYPE timestamptz USING created_at AT TIME ZONE 'UTC';


CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS ix_products_name_trgm ON products USING gin (name gin_trgm_ops);
